# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
  pod 'RxSwift', '~> 5.1.0'
  pod 'RxCocoa', '~> 5.1.0'
  pod 'TPKeyboardAvoiding'
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'Wrap', '~> 3.0.0'
  pod 'Kingfisher'
  pod 'TTGSnackbar'
end
